dist: trusty
sudo: required
language: node_js
node_js: 10.9
services:
  - docker
script:
  - scripts/test.sh
  - scripts/build.sh
deploy:
  provider: npm
  email: jasonbrooks85@gmail.com
  api_key: $NPM_TOKEN
  skip_cleanup: true
  on:
    tags: true